### PR TITLE
Implemented better algorithm to split soft body constraints into parallel groups

### PR DESCRIPTION
**Pull request by jrouwe**
This makes the soft body simulation 10-20% faster and also enables multithreading LRA, bend and volume constraints.

### CODE REVIEW

**Comment by mihe** [comment]
I haven't had time to dive into why exactly yet, but just as a heads up, I am seeing some type of regression from this change.

Before:

https://github.com/jrouwe/JoltPhysics/assets/4884246/5a71a904-f420-437e-8cca-9dfaaee019e3

After:

https://github.com/jrouwe/JoltPhysics/assets/4884246/b5dd83c7-7f62-42e3-9699-8364331ed603

Everything is obviously fine in your samples though, so I'm guessing it's gonna be something funky on my end.

**Comment by jrouwe** [comment]
Can you give me that scene?

**Comment by mihe** [comment]
Sure, here it is: [SoftBody.zip](https://github.com/jrouwe/JoltPhysics/files/14937471/SoftBody.zip)

I've omitted the `addons` folder.

You'll see some errors about "undefined behavior for SoftBody3D", but those are unrelated and have been fixed in Godot 4.3.

**Comment by jrouwe** [comment]
Hmmm, I can reproduce the issue but I have no idea why yet. I'll look at it some more tomorrow.

**Comment by jrouwe** [comment]
B.t.w. the issue seems to go away if I change:

```
const float stiffness = MAX(Math::pow(stiffness_coefficient, 3.0f) * 1000000.0f, 0.000001f);
```

to

```
const float stiffness = MAX(Math::pow(stiffness_coefficient, 3.0f) * 100000.0f, 0.000001f);
```

The order of constraint evaluation has changed by the change you mentioned.

**Pull request merged**
