### PR TITLE
Add AVX512 acceleration for double floating-point types

### PR DESCRIPTION
**Pull request by Wunkolo**

### CODE REVIEW

**Comment by Wunkolo** [comment]
Found some opportunities to utilize some AVX512 instructions that helps a bit with AVX512 performance with relation to doubles.

Tested on my i9-7900x with `cpupower frequency-set -g performance`:
```
CPU:
  Info: 10-core model: Intel Core i9-7900X bits: 64 type: MT MCP cache: L2: 10 MiB
  Speed (MHz): avg: 4226 min/max: 1200/4500 cores: 1: 1773 2: 4500 3: 4500 4: 4500 5: 4500
    6: 4500 7: 4500 8: 4500 9: 1752 10: 4500 11: 4500 12: 4500 13: 4500 14: 4500 15: 4500 16: 4500
    17: 4500 18: 4500 19: 4500 20: 4500
```

958e4115631ba5690474d1c1d5e27147497db9c3:
```
Double precision x86 64-bit with instructions: SSE2 SSE4.1 SSE4.2 AVX AVX2 AVX512 F16C LZCNT TZCNT FMADD 
Running scene: Ragdoll
Motion Quality, Thread Count, Steps / Second, Hash
ProfileMeasurement: Too many samples, some data will be lost!
Discrete, 1, 42.253007, 0x4b44be489f72020b
Discrete, 2, 57.764433, 0x4b44be489f72020b
Discrete, 3, 73.993737, 0x4b44be489f72020b
Discrete, 4, 89.494368, 0x4b44be489f72020b
Discrete, 5, 105.767015, 0x4b44be489f72020b
Discrete, 6, 121.680772, 0x4b44be489f72020b
Discrete, 7, 136.590450, 0x4b44be489f72020b
Discrete, 8, 149.230979, 0x4b44be489f72020b
Discrete, 9, 159.874752, 0x4b44be489f72020b
Discrete, 10, 170.455934, 0x4b44be489f72020b
Discrete, 11, 176.816966, 0x4b44be489f72020b
Discrete, 12, 184.344110, 0x4b44be489f72020b
Discrete, 13, 191.180913, 0x4b44be489f72020b
Discrete, 14, 196.903008, 0x4b44be489f72020b
Discrete, 15, 203.728723, 0x4b44be489f72020b
Discrete, 16, 210.236908, 0x4b44be489f72020b
Discrete, 17, 216.429502, 0x4b44be489f72020b
Discrete, 18, 222.496681, 0x4b44be489f72020b
Discrete, 19, 228.146380, 0x4b44be489f72020b
Discrete, 20, 230.806279, 0x4b44be489f72020b
LinearCast, 1, 41.468548, 0x1c322f05aaf5472a
LinearCast, 2, 56.568126, 0x1c322f05aaf5472a
LinearCast, 3, 72.271369, 0x1c322f05aaf5472a
LinearCast, 4, 86.850580, 0x1c322f05aaf5472a
LinearCast, 5, 100.772992, 0x1c322f05aaf5472a
LinearCast, 6, 114.732674, 0x1c322f05aaf5472a
LinearCast, 7, 128.743339, 0x1c322f05aaf5472a
LinearCast, 8, 140.742849, 0x1c322f05aaf5472a
LinearCast, 9, 151.033533, 0x1c322f05aaf5472a
LinearCast, 10, 159.947909, 0x1c322f05aaf5472a
LinearCast, 11, 166.405395, 0x1c322f05aaf5472a
LinearCast, 12, 173.228745, 0x1c322f05aaf5472a
LinearCast, 13, 179.003138, 0x1c322f05aaf5472a
LinearCast, 14, 185.177019, 0x1c322f05aaf5472a
LinearCast, 15, 190.447578, 0x1c322f05aaf5472a
LinearCast, 16, 195.582322, 0x1c322f05aaf5472a
LinearCast, 17, 200.956386, 0x1c322f05aaf5472a
LinearCast, 18, 205.536291, 0x1c322f05aaf5472a
LinearCast, 19, 209.700780, 0x1c322f05aaf5472a
LinearCast, 20, 212.591692, 0x1c322f05aaf5472a
```

This PR:
```
Double precision x86 64-bit with instructions: SSE2 SSE4.1 SSE4.2 AVX AVX2 AVX512 F16C LZCNT TZCNT FMADD 
Running scene: Ragdoll
Motion Quality, Thread Count, Steps / Second, Hash
ProfileMeasurement: Too many samples, some data will be lost!
Discrete, 1, 43.087973, 0x4b44be489f72020b
Discrete, 2, 58.037727, 0x4b44be489f72020b
Discrete, 3, 74.307302, 0x4b44be489f72020b
Discrete, 4, 90.089416, 0x4b44be489f72020b
Discrete, 5, 105.841057, 0x4b44be489f72020b
Discrete, 6, 122.474560, 0x4b44be489f72020b
Discrete, 7, 138.411975, 0x4b44be489f72020b
Discrete, 8, 150.523748, 0x4b44be489f72020b
Discrete, 9, 161.618542, 0x4b44be489f72020b
Discrete, 10, 172.946687, 0x4b44be489f72020b
Discrete, 11, 180.688699, 0x4b44be489f72020b
Discrete, 12, 187.462100, 0x4b44be489f72020b
Discrete, 13, 194.189360, 0x4b44be489f72020b
Discrete, 14, 199.752229, 0x4b44be489f72020b
Discrete, 15, 205.807773, 0x4b44be489f72020b
Discrete, 16, 212.553872, 0x4b44be489f72020b
Discrete, 17, 218.679433, 0x4b44be489f72020b
Discrete, 18, 224.289933, 0x4b44be489f72020b
Discrete, 19, 230.517797, 0x4b44be489f72020b
Discrete, 20, 234.528860, 0x4b44be489f72020b
LinearCast, 1, 41.129521, 0x1c322f05aaf5472a
LinearCast, 2, 56.696821, 0x1c322f05aaf5472a
LinearCast, 3, 72.682634, 0x1c322f05aaf5472a
LinearCast, 4, 87.162294, 0x1c322f05aaf5472a
LinearCast, 5, 101.297535, 0x1c322f05aaf5472a
LinearCast, 6, 115.680269, 0x1c322f05aaf5472a
LinearCast, 7, 130.793503, 0x1c322f05aaf5472a
LinearCast, 8, 142.658281, 0x1c322f05aaf5472a
LinearCast, 9, 153.233516, 0x1c322f05aaf5472a
LinearCast, 10, 163.620510, 0x1c322f05aaf5472a
LinearCast, 11, 170.228757, 0x1c322f05aaf5472a
LinearCast, 12, 176.052708, 0x1c322f05aaf5472a
LinearCast, 13, 182.178111, 0x1c322f05aaf5472a
LinearCast, 14, 188.131166, 0x1c322f05aaf5472a
LinearCast, 15, 192.543956, 0x1c322f05aaf5472a
LinearCast, 16, 198.734050, 0x1c322f05aaf5472a
LinearCast, 17, 203.016436, 0x1c322f05aaf5472a
LinearCast, 18, 207.394086, 0x1c322f05aaf5472a
LinearCast, 19, 212.401466, 0x1c322f05aaf5472a
LinearCast, 20, 214.342987, 0x1c322f05aaf5472a
```

**Comment by jrouwe** [comment]
Thanks!

B.t.w. profiling is best done in the Distribution configuration. The profiling code has some overhead and I can see it's on because of the following trace:

```
ProfileMeasurement: Too many samples, some data will be lost!
```

**Comment by jenetscaria-mcw** [comment]
> Thanks!
> 
> B.t.w. profiling is best done in the Distribution configuration. The profiling code has some overhead and I can see it's on because of the following trace:
> 
> ```
> ProfileMeasurement: Too many samples, some data will be lost!
> ```

@jrouwe Hi we are trying to analyze the AVX2 and AVX512 versions for the code. Based on above comment, we compared across Release and Distribution configurations. We have seen significant gains with Distribution configuration. We would require your help in understanding what exactly goes on during Distribution configuration. Any help would be appreciated. Thanks.

**Comment by jrouwe** [comment]
The difference between Release and Distribution is that Release has ```JPH_PROFILE_ENABLED``` and ```JPH_DEBUG_RENDERER``` defined and Distribution not. Both cause some overhead in the physics simulation so Distribution is the fastest build.

**Pull request merged**
