### PR TITLE
minor improvements and better nesting structure to architecture docs page

### PR DESCRIPTION
**Pull request by cuppajoeman**
Old Structure:

image

New structure:
image

The benefit of the new structure is that there are less top level structures so that you can find a specific topic faster as you don't have to scan irrelevant information when searching for a topic

### CODE REVIEW

**Comment by jrouwe** [comment]
Hello,

Images/EllipsoidAABB.png is missing from the change.

Also I get an error:

```
Architecture.md:332: error: unable to resolve reference to 'basics' for \ref command
```

I'm not sure what you intended to refer to.

W.r.t. the content changes: The section about quad tree is a bit misleading as this is not how Jolt's quad tree works. See page 20 of [my GDC talk](https://jrouwe.nl/architectingjolt/ArchitectingJoltPhysics_Rouwe_Jorrit_Notes.pdf).

**Comment by cuppajoeman** [comment]
Hi Jorrit,

Yes looks like I forgot to add a link to that, I'll correct the broken basics link (the basics file was the one I created in the other pull request, so I can remove that reference). 

As for the quadtree, I'll remove what I wrote for this commit, when I have a better understanding of what's in the GDC talk I can re-add the section.

**Comment by cuppajoeman** [comment]
I've implemented the requested changes that you asked for. Also note that there is a section on grids, even though Jolt doesn't use grids. My reasoning was it would help motivate why we use quadtree's for spatial partitioning. Let me know if this is alright or if you need further changes.

**Comment by cuppajoeman** [comment]
> Please hold on, I need some time to take a look at this.

If going through it is too much of a hassle I can move the content to my personal site as well. :+1:

**Comment by jrouwe** [comment]
I did some further editing on this. Hopefully you won't disagree with my changes. I'm trying to keep the document short and relevant for people who have worked in the gaming industry for a while.

**Comment by cuppajoeman** [comment]
> I did some further editing on this. Hopefully you won't disagree with my changes. I'm trying to keep the document short and relevant for people who have worked in the gaming industry for a while.

Hey @jrouwe, no problem at all. Looking at it now I think it reads better. 

When I initially started making my docs edits I thought that adding extra information would be useful for the beginner, while it might be, I can see now that Jolt documentation should document unique things about Jolt (and other sources can document their own specific things) so I apologize if my merge requests were not helpful.

**Pull request merged**
